"""XBRL fact — XBRL 2.1 §4.6.

A :class:`Fact` is the mutable data record for one reported value.  It is
intentionally *not* frozen because parser stages may enrich facts after
initial construction (e.g. applying iXBRL transforms or assigning
synthetic IDs).

All numeric values are stored as :class:`decimal.Decimal` — **never** as
``float`` — to preserve the precision semantics mandated by
XBRL 2.1 §4.6.6.

References:
    - XBRL 2.1 §4.6   (item element)
    - XBRL 2.1 §4.6.3 (numeric items)
    - XBRL 2.1 §4.6.6 (decimals / precision)
    - Inline XBRL 1.1 §4.7 (ix:nonFraction, scale, sign, format)
"""

from __future__ import annotations

from dataclasses import dataclass
from decimal import Decimal

from src.core.types import FactType


@dataclass(slots=True)
class Fact:
    """A single XBRL fact (reported value) — XBRL 2.1 §4.6.

    Attributes:
        fact_id: Unique identifier.  May be the XML ``id`` attribute or
            a synthetic ID generated by the parser.
        concept_qname: Clark-notation QName of the concept this fact
            reports (e.g. ``"{http://fasb.org/us-gaap/2024}Assets"``).
        context_ref: ``contextRef`` attribute — references a
            :pydata:`src.core.types.ContextID`.
        unit_ref: ``unitRef`` attribute for numeric facts; ``None`` for
            non-numeric facts.
        value: Parsed value.  :class:`~decimal.Decimal` for numeric
            facts, ``str`` for non-numeric facts, ``None`` for nil
            facts.
        fact_type: Category discriminator.
        decimals: ``decimals`` attribute value (``None`` if absent or
            non-numeric) — XBRL 2.1 §4.6.6.
        precision: ``precision`` attribute value (deprecated but
            supported) — XBRL 2.1 §4.6.6.
        is_nil: ``True`` when ``xsi:nil="true"`` is set on the element.
        language: ``xml:lang`` attribute value, if present.
        source_line: 1-based line number in the source document (for
            error-reporting).
        source_file: Path or URL of the source document.
        format_code: Inline XBRL transformation format code
            (e.g. ``"ixt:num-dot-decimal"``) — Inline XBRL 1.1 §4.7.
        scale: ``scale`` attribute from ``ix:nonFraction`` — Inline
            XBRL 1.1 §4.7.4.
        sign: ``sign`` attribute from ``ix:nonFraction`` — Inline
            XBRL 1.1 §4.7.4.  ``"-"`` for negative, ``None`` otherwise.
    """

    fact_id: str
    concept_qname: str
    context_ref: str
    unit_ref: str | None
    value: Decimal | str | None
    fact_type: FactType
    decimals: int | None
    precision: int | None
    is_nil: bool
    language: str | None
    source_line: int | None
    source_file: str

    # iXBRL-specific attributes
    format_code: str | None = None
    scale: int | None = None
    sign: str | None = None

    @property
    def is_numeric(self) -> bool:
        """Return ``True`` if this fact carries a numeric value.

        Numeric facts have ``fact_type`` of :attr:`FactType.NUMERIC` or
        :attr:`FactType.FRACTION` — XBRL 2.1 §4.6.3.

        Returns:
            ``True`` for numeric (including fraction) facts.
        """
        return self.fact_type in (FactType.NUMERIC, FactType.FRACTION)

    def effective_value(self) -> Decimal | str | None:
        """Return the value after applying iXBRL scale and sign transforms.

        For numeric facts with ``scale`` and/or ``sign`` attributes set,
        the returned :class:`~decimal.Decimal` reflects:

        1. Multiplication by ``10 ** scale`` (if *scale* is not ``None``).
        2. Negation (if *sign* is ``"-"``).

        Non-numeric or nil facts are returned unchanged.

        Returns:
            The effective typed value.

        References:
            - Inline XBRL 1.1 §4.7.4
        """
        if not self.is_numeric or self.value is None:
            return self.value

        if not isinstance(self.value, Decimal):
            return self.value

        result: Decimal = self.value
        if self.scale is not None:
            result = result * Decimal(10) ** self.scale
        if self.sign == "-":
            result = -result
        return result
